#Catppuccin Mocha
# by Catppuccin Org (https://github.com/catppuccin/btop)
# Manually synced into dotfiles so it works on machines with no net at boot.

# Main bg
theme[main_bg]="#1e1e2e"

# Main text color
theme[main_fg]="#cdd6f4"

# Title color for boxes
theme[title]="#cdd6f4"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#cba6f7"

# Background color of selected item in processes box
theme[selected_bg]="#585b70"

# Foreground color of selected item in processes box
theme[selected_fg]="#cba6f7"

# Color of inactive/disabled text
theme[inactive_fg]="#7f849c"

# Color of text appearing on top of graphs
theme[graph_text]="#f5e0dc"

# Misc colors for processes box
theme[proc_misc]="#f5e0dc"

# Cpu box outline color
theme[cpu_box]="#cba6f7"

# Memory/disks box outline color
theme[mem_box]="#a6e3a1"

# Net up/down box outline color
theme[net_box]="#f38ba8"

# Processes box outline color
theme[proc_box]="#89b4fa"

# Box divider line and small boxes line color
theme[div_line]="#585b70"

# Temperature graph colors
theme[temp_start]="#a6e3a1"
theme[temp_mid]="#f9e2af"
theme[temp_end]="#f38ba8"

# CPU graph colors
theme[cpu_start]="#94e2d5"
theme[cpu_mid]="#89dceb"
theme[cpu_end]="#74c7ec"

# Mem/Disk free meter
theme[free_start]="#89b4fa"
theme[free_mid]="#b4befe"
theme[free_end]="#cba6f7"

# Mem/Disk cached meter
theme[cached_start]="#74c7ec"
theme[cached_mid]="#89b4fa"
theme[cached_end]="#b4befe"

# Mem/Disk available meter
theme[available_start]="#f9e2af"
theme[available_mid]="#fab387"
theme[available_end]="#f38ba8"

# Mem/Disk used meter
theme[used_start]="#a6e3a1"
theme[used_mid]="#94e2d5"
theme[used_end]="#74c7ec"

# Download graph colors
theme[download_start]="#89b4fa"
theme[download_mid]="#b4befe"
theme[download_end]="#cba6f7"

# Upload graph colors
theme[upload_start]="#f2cdcd"
theme[upload_mid]="#eba0ac"
theme[upload_end]="#f38ba8"

# Process box color gradient for threads, memory and cpu usage
theme[process_start]="#a6e3a1"
theme[process_mid]="#74c7ec"
theme[process_end]="#89b4fa"
