# shellcheck shell=bash
# scripts/lib/ai-prefs.sh — local per-user/per-machine preferences for `mesh ai`.
# Source-only (no top-level execution).
#
# These are workstation-local UX preferences, not synced identity data. The file
# is intentionally under ~/.config/mesh so changing the default on one machine
# does not rewrite mesh-identity or affect other hosts.

ai_prefs_file() {
    printf '%s' "${MESH_AI_PREFS:-${XDG_CONFIG_HOME:-$HOME/.config}/mesh/ai.env}"
}

ai_prefs_load() {
    local f
    f="$(ai_prefs_file)"
    [[ -r "$f" ]] || return 0
    # shellcheck disable=SC1090
    . "$f"
    export MESH_AI_DEFAULT_AGENT MESH_AI_DEFAULT_ACTION MESH_AI_OPEN_EXISTING
}

ai_pref_default_action() {
    case "${MESH_AI_DEFAULT_ACTION:-agent}" in
        shell) printf 'shell' ;;
        *)     printf 'agent' ;;
    esac
}

ai_pref_open_existing() {
    case "${MESH_AI_OPEN_EXISTING:-focus}" in
        new) printf 'new' ;;
        *)   printf 'focus' ;;
    esac
}

ai_prefs_set() {
    local key="$1" value="$2" f tmp
    case "$key" in
        MESH_AI_DEFAULT_AGENT|MESH_AI_DEFAULT_ACTION|MESH_AI_OPEN_EXISTING) ;;
        *) return 2 ;;
    esac
    case "$value" in
        *[!A-Za-z0-9_-]*|'') return 2 ;;
    esac

    f="$(ai_prefs_file)"
    mkdir -p "$(dirname "$f")" || return 1
    tmp="$(mktemp "${f}.XXXXXX")" || return 1
    if [[ -r "$f" ]]; then
        awk -F= -v k="$key" -v v="$value" '
            $1 == k { print k "=" v; done=1; next }
            { print }
            END { if (!done) print k "=" v }
        ' "$f" > "$tmp"
    else
        {
            printf '# ~/.config/mesh/ai.env — local preferences for `mesh ai`.\n'
            printf '# Machine-local; generated by the picker UI.\n'
            printf '%s=%s\n' "$key" "$value"
        } > "$tmp"
    fi
    mv "$tmp" "$f" || { rm -f "$tmp"; return 1; }
}
