#!/usr/bin/env bash
# scripts/lib/catalog.sh — derive .catalog/ from repo sources.
#
# Produces 4 derived files + 1 README index. Output is byte-stable across
# re-runs: every collector pipes through `sort` (or `sort -u`) and never
# emits timestamps. CI can diff two runs to verify drift.
#
# Outputs in $ROOT/.catalog/:
#   resources.txt  files under topics/*/resources/
#   opt-ins.txt    INCLUDE_* env-var toggles surfaced anywhere in scripts/topics
#   cli.txt        mesh subcommands (parsed from bin/mesh case dispatch)
#   drivers.txt    installer driver names (scripts/lib/installers/*.sh)
#   README.md      hand-readable index + pointer to curated narrative at
#                  docs/catalog/behaviors.md (hand-maintained, out-of-scope here)
#
# Spec: §C22. Phase 5 Task 5.3.

set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
OUT="$ROOT/.catalog"

mkdir -p "$OUT"

# ─── resources.txt ─────────────────────────────────────────────────
# Files living under topics/*/resources/ (data files shipped with topics).
# Skip-if-absent: tree may have no resources/ dirs yet.
find "$ROOT/topics" -path '*/resources/*' -type f 2>/dev/null \
    | sed "s|^$ROOT/||" \
    | LC_ALL=C sort \
    > "$OUT/resources.txt"

# ─── opt-ins.txt ───────────────────────────────────────────────────
# Every INCLUDE_<NAME> toggle name found in scripts/topics/bin sources.
grep -rhoE '\bINCLUDE_[A-Z][A-Z0-9_]*' \
    --include='*.sh' --include='*.zsh' \
    --exclude-dir=tests --exclude-dir=.git --exclude-dir=archive \
    "$ROOT/scripts" "$ROOT/topics" "$ROOT/bin" 2>/dev/null \
    | LC_ALL=C sort -u \
    > "$OUT/opt-ins.txt"

# ─── cli.txt ───────────────────────────────────────────────────────
# mesh subcommands taken from the case dispatch block in bin/mesh.
# We rely on the convention that each subcommand case label sits at the
# start of its own line as "    <name>)".
if [[ -f "$ROOT/bin/mesh" ]]; then
    grep -E '^    [a-z][a-z-]+\)$' "$ROOT/bin/mesh" \
        | sed -E 's/^[[:space:]]+//; s/\)$//' \
        | LC_ALL=C sort -u \
        > "$OUT/cli.txt"
else
    : > "$OUT/cli.txt"
fi

# ─── drivers.txt ───────────────────────────────────────────────────
# Installer drivers. Strip directory + .sh extension to leave the name only.
if [[ -d "$ROOT/scripts/lib/installers" ]]; then
    find "$ROOT/scripts/lib/installers" -maxdepth 1 -type f -name '*.sh' 2>/dev/null \
        | sed -E "s|.*/||; s|\.sh$||" \
        | LC_ALL=C sort \
        > "$OUT/drivers.txt"
else
    : > "$OUT/drivers.txt"
fi

# ─── README.md ─────────────────────────────────────────────────────
# Static index. No timestamps; count lines from the four derived files so
# the index reflects current content but stays byte-stable per re-run.
res_n=$(wc -l < "$OUT/resources.txt" | tr -d ' ')
opt_n=$(wc -l < "$OUT/opt-ins.txt"   | tr -d ' ')
cli_n=$(wc -l < "$OUT/cli.txt"       | tr -d ' ')
drv_n=$(wc -l < "$OUT/drivers.txt"   | tr -d ' ')

cat > "$OUT/README.md" <<EOF
# .catalog/

Auto-generated by \`mesh catalog generate\` (\`scripts/lib/catalog.sh\`).
Re-generation is byte-stable: two consecutive runs produce identical output.

## Derived files

| File | Lines | Source |
|---|---:|---|
| [resources.txt](resources.txt) | $res_n | \`topics/*/resources/\` |
| [opt-ins.txt](opt-ins.txt) | $opt_n | \`INCLUDE_*\` toggles in scripts/topics |
| [cli.txt](cli.txt) | $cli_n | \`mesh\` subcommands in bin/mesh case dispatch |
| [drivers.txt](drivers.txt) | $drv_n | \`scripts/lib/installers/*.sh\` |

## Curated narrative

Hand-maintained narrative lives at \`docs/catalog/behaviors.md\` (out of
scope for this generator — kept editable so the operator can describe
non-derivable invariants, decision-rationale, and inter-topic behavior).

Spec: §C22.
EOF

echo "[catalog] wrote $OUT/{resources,opt-ins,cli,drivers}.txt + README.md"
