#!/usr/bin/env bash
# lib/launch-wrapper.sh — user-scope LaunchAgent generator that wraps brew
# binaries living in non-canonical prefixes (e.g. /Volumes/External/homebrew).
#
# WHY: macOS TCC sandbox blocks user-scope LaunchAgents whose
# ProgramArguments[0] is in a `noowners` volume — exit 78 EX_CONFIG even
# when the binary is executable and exists. A wrapper script in rootfs
# (~/.local/bin or /usr/local/bin) passes the spawn-time TCC check; the
# subsequent `exec` into the external binary preserves the granted
# entitlement. Empirically validated 2026-05-03 (Mac M2, Sequoia, brew in
# /Volumes/External/homebrew).
#
# Source from a topic; do not execute directly.
# On non-Mac, all public functions noop and return 0, except dry-run tests
# which still generate files without invoking launchctl.
#
# Public API:
#   launch_wrapper_install_extbrew --svc NAME --label LABEL --brew-bin PATH \
#       [--workdir DIR] [--env KEY=VAL ...] -- arg1 arg2 ...
#   launch_wrapper_teardown <label>          (bootout + rm wrapper + plist)
#   launch_wrapper_teardown_homebrew_plist <svc>  (bootout + rename .bak)
#
# Test hook:
#   LAUNCH_WRAPPER_DRY_RUN=1   skip the launchctl bootstrap step

[ -n "${_LAUNCH_WRAPPER_LOADED:-}" ] && return 0
_LAUNCH_WRAPPER_LOADED=1

# ---------- Paths (overridable for tests) ----------
LAUNCH_WRAPPER_BIN_DIR="${LAUNCH_WRAPPER_BIN_DIR:-$HOME/.local/bin}"
LAUNCH_WRAPPER_LOG_DIR="${LAUNCH_WRAPPER_LOG_DIR:-$HOME/.local/share/launch-wrapper}"
LAUNCH_WRAPPER_PLIST_DIR="${LAUNCH_WRAPPER_PLIST_DIR:-$HOME/Library/LaunchAgents}"

# ---------- Internals ----------
_launch_wrapper_is_mac() {
    [[ "$(uname -s)" == "Darwin" ]]
}

_launch_wrapper_should_run() {
    _launch_wrapper_is_mac || [[ -n "${LAUNCH_WRAPPER_DRY_RUN:-}" ]]
}

_launch_wrapper_script_path() {
    printf '%s/%s-extbrew-wrapper.sh' "$LAUNCH_WRAPPER_BIN_DIR" "$1"
}

_launch_wrapper_plist_path() {
    printf '%s/%s.plist' "$LAUNCH_WRAPPER_PLIST_DIR" "$1"
}

# Write the wrapper script. Idempotent — overwrites.
# Wrapper waits for external volume to mount (defense against D42 phantom
# mkdir family — early-boot launchd kicks before disk decrypt completes)
# then exec's the brew binary, inheriting TCC entitlement.
#
# Args:
#   $1 = svc
#   $2 = brew_bin (full path)
#   $3+ = args to pass (each will be %q-quoted into the wrapper)
_launch_wrapper_write_script() {
    local svc="$1" brew_bin="$2"
    shift 2

    mkdir -p "$LAUNCH_WRAPPER_BIN_DIR" "$LAUNCH_WRAPPER_LOG_DIR"
    local script_path
    script_path="$(_launch_wrapper_script_path "$svc")"

    # Build a single quoted args string for embedding.
    local args_str="" arg esc
    for arg in "$@"; do
        printf -v esc '%q' "$arg"
        args_str+=" $esc"
    done

    # heredoc: 'WRAPPER' (quoted) prevents shell expansion in the body —
    # safer & idempotent. Fields are interpolated by sed below.
    local tmp="${script_path}.tmp.$$"
    cat > "$tmp" <<'WRAPPER'
#!/bin/bash
# launch-wrapper for __SVC__ — generated by mesh-workstation/lib/launch-wrapper.sh.
# DO NOT EDIT BY HAND — regenerated on every mesh-workstation run.
#
# Why this exists: macOS TCC sandbox blocks user-scope LaunchAgents whose
# ProgramArguments path is in /Volumes/<noowners>. Wrapper in rootfs passes
# TCC's spawn-time check; entitlement is preserved across execve into the
# external binary.

set -u
target='__BREW_BIN__'

# Wait up to 30s for the external volume to finish mounting (defense
# against early-boot timing — D42 family of bugs).
i=0
while [[ $i -lt 30 ]]; do
    [[ -x "$target" ]] && break
    sleep 1
    i=$((i + 1))
done

if [[ ! -x "$target" ]]; then
    echo "[launch-wrapper:__SVC__] target binary missing after 30s wait: $target" >&2
    exit 78
fi

exec "$target"__ARGS__
WRAPPER

    # Inline-substitute placeholders. Use a delimiter unlikely to appear.
    # `|` is safe in svc names and binary paths (we don't allow them in svc;
    # paths use `/` and alphanumerics). For args_str, since `%q` may emit
    # `|` in pathological cases we use `@` as the sed delimiter.
    sed -i.bak \
        -e "s@__SVC__@${svc//@/\\@}@g" \
        -e "s@__BREW_BIN__@${brew_bin//@/\\@}@g" \
        -e "s@__ARGS__@${args_str//@/\\@}@" \
        "$tmp"
    rm -f "${tmp}.bak"

    mv "$tmp" "$script_path"
    chmod 0755 "$script_path"
}

# Write the user-scope plist. Idempotent — overwrites.
# Args:
#   $1 = label
#   $2 = wrapper_path
#   $3 = workdir (may be empty)
#   $4+ = "KEY=VAL" env var pairs (may be zero)
_launch_wrapper_write_plist() {
    local label="$1" wrapper="$2" workdir="$3"
    shift 3

    mkdir -p "$LAUNCH_WRAPPER_PLIST_DIR" "$LAUNCH_WRAPPER_LOG_DIR"
    local plist_path svc log_out log_err
    plist_path="$(_launch_wrapper_plist_path "$label")"
    svc="${label##*.}"
    log_out="$LAUNCH_WRAPPER_LOG_DIR/${svc}.log"
    log_err="$LAUNCH_WRAPPER_LOG_DIR/${svc}.err"

    {
        printf '<?xml version="1.0" encoding="UTF-8"?>\n'
        printf '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" '
        printf '"http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n'
        printf '<plist version="1.0">\n<dict>\n'
        printf '    <key>Label</key>\n    <string>%s</string>\n' "$label"
        printf '    <key>ProgramArguments</key>\n    <array>\n'
        printf '        <string>%s</string>\n' "$wrapper"
        printf '    </array>\n'
        printf '    <key>RunAtLoad</key>\n    <true/>\n'
        printf '    <key>KeepAlive</key>\n    <true/>\n'
        printf '    <key>StandardOutPath</key>\n    <string>%s</string>\n' "$log_out"
        printf '    <key>StandardErrorPath</key>\n    <string>%s</string>\n' "$log_err"
        if [[ -n "$workdir" ]]; then
            printf '    <key>WorkingDirectory</key>\n    <string>%s</string>\n' "$workdir"
        fi
        if [[ "$#" -gt 0 ]]; then
            printf '    <key>EnvironmentVariables</key>\n    <dict>\n'
            local kv k v
            for kv in "$@"; do
                k="${kv%%=*}"
                v="${kv#*=}"
                printf '        <key>%s</key>\n        <string>%s</string>\n' "$k" "$v"
            done
            printf '    </dict>\n'
        fi
        printf '</dict>\n</plist>\n'
    } > "$plist_path"
}

# Bootstrap (or re-bootstrap) a user-scope plist. Idempotent.
_launch_wrapper_bootstrap() {
    local label="$1" plist
    plist="$(_launch_wrapper_plist_path "$label")"
    local uid
    uid=$(id -u)

    if [[ -n "${LAUNCH_WRAPPER_DRY_RUN:-}" ]]; then
        return 0
    fi

    if launchctl print "gui/${uid}/${label}" >/dev/null 2>&1; then
        launchctl bootout "gui/${uid}/${label}" 2>/dev/null || true
        # bootout is async — wait briefly for actual unload
        local _wait
        for _wait in 1 2 3 4 5; do
            launchctl print "gui/${uid}/${label}" >/dev/null 2>&1 || break
            sleep 1
        done
    fi

    launchctl bootstrap "gui/${uid}" "$plist"
}

# ---------- Public API ----------

# Tear down a homebrew.mxcl.<svc>.plist that we're replacing with our wrapper.
# bootout + rename to .bak so brew can detect & restore if user wants.
launch_wrapper_teardown_homebrew_plist() {
    _launch_wrapper_should_run || return 0
    local svc="$1"
    local label="homebrew.mxcl.${svc}"
    local plist="$LAUNCH_WRAPPER_PLIST_DIR/${label}.plist"
    local uid
    uid=$(id -u)

    if [[ -z "${LAUNCH_WRAPPER_DRY_RUN:-}" ]]; then
        if launchctl print "gui/${uid}/${label}" >/dev/null 2>&1; then
            launchctl bootout "gui/${uid}/${label}" 2>/dev/null || true
        fi
    fi
    if [[ -f "$plist" ]]; then
        # Don't double-bak: if .bak already exists, leave the old one alone.
        if [[ ! -f "${plist}.bak" ]]; then
            mv "$plist" "${plist}.bak"
        else
            rm -f "$plist"
        fi
    fi
}

# Tear down a wrapper-managed plist (e.g. com.<user>.<svc>). Removes plist,
# wrapper script, and bootouts. Used by uninstall flows.
launch_wrapper_teardown() {
    _launch_wrapper_should_run || return 0
    local label="$1"
    local svc="${label##*.}"
    local plist
    plist="$(_launch_wrapper_plist_path "$label")"
    local script_path
    script_path="$(_launch_wrapper_script_path "$svc")"
    local uid
    uid=$(id -u)

    if [[ -z "${LAUNCH_WRAPPER_DRY_RUN:-}" ]]; then
        if launchctl print "gui/${uid}/${label}" >/dev/null 2>&1; then
            launchctl bootout "gui/${uid}/${label}" 2>/dev/null || true
        fi
    fi
    rm -f "$plist" "$script_path"
}

# Install a user-scope LaunchAgent that wraps a brew binary.
# Tears down any existing homebrew.mxcl.<svc>.plist (renamed .bak).
#
# Required:
#   --svc NAME           short svc name (used in filenames + log paths)
#   --label LABEL        plist label (e.g. com.<user>.<svc>)
#   --brew-bin PATH      full path to brew binary
#
# Optional:
#   --workdir DIR        WorkingDirectory in plist
#   --env KEY=VAL        repeatable; sets EnvironmentVariables in plist
#
# After `--`, all args are passed to the brew binary at exec time.
#
# Example:
#   launch_wrapper_install_extbrew \
#       --svc syncthing \
#       --label com.henryavila.syncthing \
#       --brew-bin /Volumes/External/homebrew/bin/syncthing \
#       -- serve --no-browser --no-restart
launch_wrapper_install_extbrew() {
    _launch_wrapper_should_run || return 0

    local svc="" label="" brew_bin="" workdir=""
    local -a env_vars
    env_vars=()

    while [[ "$#" -gt 0 ]]; do
        case "$1" in
            --svc)      svc="$2"; shift 2 ;;
            --label)    label="$2"; shift 2 ;;
            --brew-bin) brew_bin="$2"; shift 2 ;;
            --workdir)  workdir="$2"; shift 2 ;;
            --env)      env_vars+=("$2"); shift 2 ;;
            --)         shift; break ;;
            *)
                printf 'launch_wrapper_install_extbrew: unknown arg: %s\n' "$1" >&2
                return 1
                ;;
        esac
    done

    if [[ -z "$svc" || -z "$label" || -z "$brew_bin" ]]; then
        printf 'launch_wrapper_install_extbrew: missing required --svc/--label/--brew-bin\n' >&2
        return 1
    fi

    # Tear down brew's plist for this svc (idempotent — noop if absent).
    launch_wrapper_teardown_homebrew_plist "$svc"

    local wrapper_path
    wrapper_path="$(_launch_wrapper_script_path "$svc")"

    _launch_wrapper_write_script "$svc" "$brew_bin" "$@"
    # Bash 3.2 quirk: `"${arr[@]+"${arr[@]}"}"` expands to one empty arg when
    # the array is empty (not zero args, as in bash 4+). The empty arg
    # propagates into the plist's EnvironmentVariables dict as `<key></key>
    # <string></string>`, which is malformed XML — launchd rejects with
    # EX_CONFIG (exit 78). Guard explicitly on array length.
    if [[ ${#env_vars[@]} -gt 0 ]]; then
        _launch_wrapper_write_plist "$label" "$wrapper_path" "$workdir" "${env_vars[@]}"
    else
        _launch_wrapper_write_plist "$label" "$wrapper_path" "$workdir"
    fi
    _launch_wrapper_bootstrap "$label"
}
