import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { homedir } from 'node:os';

const CONFIG_DIR = join(
  process.env.XDG_CONFIG_HOME ?? join(homedir(), '.config'),
  'mesh',
);
const SELECTIONS_PATH = join(CONFIG_DIR, 'selections.list');
const PARAMS_PATH = join(CONFIG_DIR, 'params.env');

export function readSelections(path = SELECTIONS_PATH) {
  try {
    const content = readFileSync(path, 'utf8');
    return content
      .split('\n')
      .map((l) => l.trim())
      .filter((l) => l && !l.startsWith('#'));
  } catch {
    return null;
  }
}

export function writeSelections(entries, path = SELECTIONS_PATH) {
  mkdirSync(dirname(path), { recursive: true });
  const header = '# Auto-generated by mesh menu. Hand-editable.\n# One item per line: topic/item-name\n# Regenerate: mesh menu\n';
  const content = header + entries.join('\n') + '\n';
  writeFileSync(path, content, 'utf8');
}

export function readParams(path = PARAMS_PATH) {
  try {
    const content = readFileSync(path, 'utf8');
    const params = {};
    for (const line of content.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const eq = trimmed.indexOf('=');
      if (eq < 0) continue;
      const key = trimmed.slice(0, eq);
      let val = trimmed.slice(eq + 1);
      val = val.replace(/^["']|["']$/g, '');
      params[key] = val;
    }
    return params;
  } catch {
    return {};
  }
}

export function writeParams(params, path = PARAMS_PATH) {
  mkdirSync(dirname(path), { recursive: true });
  const lines = ['# Auto-generated by mesh menu.'];
  for (const [key, val] of Object.entries(params)) {
    const needsQuote = /\s/.test(val);
    lines.push(needsQuote ? `${key}="${val}"` : `${key}=${val}`);
  }
  writeFileSync(path, lines.join('\n') + '\n', 'utf8');
}

export function selectionsToMap(entries) {
  const map = new Map();
  for (const entry of entries) {
    const slash = entry.indexOf('/');
    if (slash < 0) continue;
    const topic = entry.slice(0, slash);
    const item = entry.slice(slash + 1);
    if (!map.has(topic)) map.set(topic, new Set());
    map.get(topic).add(item);
  }
  return map;
}

export { SELECTIONS_PATH, PARAMS_PATH, CONFIG_DIR };
